pipeline:
  get_geoip_databases:
    image: docker
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - GEOIP_LICENSE_KEY
    commands:
      - export GEOIP_CITY_URL='https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$${GEOIP_LICENSE_KEY}&suffix=tar.gz'
      - export GEOIP_COUNTRY_URL='https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$${GEOIP_LICENSE_KEY}&suffix=tar.gz'
      - curl -fSL ${GEOIP_COUNTRY_URL} | gzip -d > GeoLite2-Country.mmdb
      - curl -fSL ${GEOIP_CITY_URL} | gzip -d > GeoLite2-City.mmdb
    when:
      event: push

  build_and_test_image:
    image: quay.io/ukhomeofficedigital/centos-base:latest
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - yum update -y
      - yum install -y -q docker openssl wget
      - mkdir -p /usr/share/GeoIP
      - cp GeoLite2*.mmdb /usr/share/GeoIP
      - ./ci-build.sh
    when:
      event: push

  push_image_to_quay:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - b${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master
