pipeline:
  build_and_test_image:
    image: quay.io/ukhomeofficedigital/centos-base:latest
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - yum update -y
      - yum install -y -q docker openssl wget
      - ./ci-build.sh
      - export GEOIP_LICENSE_KEY=$$GEOIP_LICENSE_KEY
    secrets:
      - GEOIP_LICENSE_KEY
    when:
      event: push

  push_image_to_quay:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - b${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master
