---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: get_geoip_databases
  pull: if-not-exists
  image: plugins/docker
  commands:
  - apk add curl
  - curl -fSL $${GEOIP_CITY_URL} | gzip -d > GeoLite2-City.mmdb
  - curl -fSL $${GEOIP_COUNTRY_URL} | gzip -d > GeoLite2-Country.mmdb
  environment:
    GEOIP_CITY_URL:
      from_secret: GEOIP_CITY_URL
    GEOIP_COUNTRY_URL:
      from_secret: GEOIP_COUNTRY_URL
  when:
    event:
    - push

- name: build_image
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect
    tags:
    - ${DRONE_COMMIT_SHA}
    - dev-${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:$${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: tag_master_code_image
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - docker tag quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:latest
  - docker tag quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:b${DRONE_BUILD_NUMBER}
  when:
    # branch:
    # - master
    event:
    - promote
    target:
    - production  

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
